//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int AdvId { get; set; }
        public string No { get; set; }
        public string Header { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Details { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<bool> State { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
